-- Police forces in England (data.police.uk force slugs).
-- Generated by data/build_police.mjs on 2026-09-26 from https://data.police.uk/api/forces (fetched 2026-09-26). Do not edit by hand.
-- Excludes Welsh forces (dyfed-powys, gwent, north-wales, south-wales) and PSNI.
-- report_url is the force website (the API exposes no reporting URL); non_emergency_url is tel:101.

insert into police_forces (id, name, report_url, non_emergency_url) values
  ('avon-and-somerset', 'Avon and Somerset Constabulary', 'https://www.avonandsomerset.police.uk/', 'tel:101'),
  ('bedfordshire', 'Bedfordshire Police', 'https://www.beds.police.uk/', 'tel:101'),
  ('cambridgeshire', 'Cambridgeshire Constabulary', 'https://www.cambs.police.uk/', 'tel:101'),
  ('cheshire', 'Cheshire Constabulary', 'https://www.cheshire.police.uk/', 'tel:101'),
  ('city-of-london', 'City of London Police', 'https://www.cityoflondon.police.uk/', 'tel:101'),
  ('cleveland', 'Cleveland Police', 'https://www.cleveland.police.uk/', 'tel:101'),
  ('cumbria', 'Cumbria Constabulary', 'https://www.cumbria.police.uk/', 'tel:101'),
  ('derbyshire', 'Derbyshire Constabulary', 'https://www.derbyshire.police.uk/', 'tel:101'),
  ('devon-and-cornwall', 'Devon & Cornwall Police', 'https://www.devon-cornwall.police.uk/', 'tel:101'),
  ('dorset', 'Dorset Police', 'https://www.dorset.police.uk/', 'tel:101'),
  ('durham', 'Durham Constabulary', 'https://www.durham.police.uk/', 'tel:101'),
  ('essex', 'Essex Police', 'https://www.essex.police.uk/', 'tel:101'),
  ('gloucestershire', 'Gloucestershire Constabulary', 'https://www.gloucestershire.police.uk/', 'tel:101'),
  ('greater-manchester', 'Greater Manchester Police', 'https://www.gmp.police.uk/', 'tel:101'),
  ('hampshire', 'Hampshire Constabulary', 'https://www.hampshire.police.uk/', 'tel:101'),
  ('hertfordshire', 'Hertfordshire Constabulary', 'https://www.herts.police.uk/', 'tel:101'),
  ('humberside', 'Humberside Police', 'https://www.humberside.police.uk/', 'tel:101'),
  ('kent', 'Kent Police', 'https://www.kent.police.uk/', 'tel:101'),
  ('lancashire', 'Lancashire Constabulary', 'https://www.lancashire.police.uk/', 'tel:101'),
  ('leicestershire', 'Leicestershire Police', 'https://www.leics.police.uk/', 'tel:101'),
  ('lincolnshire', 'Lincolnshire Police', 'https://www.lincs.police.uk/', 'tel:101'),
  ('merseyside', 'Merseyside Police', 'https://www.merseyside.police.uk/', 'tel:101'),
  ('metropolitan', 'Metropolitan Police Service', 'https://www.met.police.uk/', 'tel:101'),
  ('norfolk', 'Norfolk Constabulary', 'https://www.norfolk.police.uk/', 'tel:101'),
  ('north-yorkshire', 'North Yorkshire Police', 'https://www.northyorkshire.police.uk/', 'tel:101'),
  ('northamptonshire', 'Northamptonshire Police', 'https://www.northants.police.uk/', 'tel:101'),
  ('northumbria', 'Northumbria Police', 'https://www.northumbria.police.uk/', 'tel:101'),
  ('nottinghamshire', 'Nottinghamshire Police', 'https://www.nottinghamshire.police.uk/', 'tel:101'),
  ('south-yorkshire', 'South Yorkshire Police', 'https://www.southyorkshire.police.uk/', 'tel:101'),
  ('staffordshire', 'Staffordshire Police', 'https://www.staffordshire.police.uk/', 'tel:101'),
  ('suffolk', 'Suffolk Constabulary', 'https://www.suffolk.police.uk/', 'tel:101'),
  ('surrey', 'Surrey Police', 'https://www.surrey.police.uk/', 'tel:101'),
  ('sussex', 'Sussex Police', 'https://www.sussex.police.uk/', 'tel:101'),
  ('thames-valley', 'Thames Valley Police', 'https://www.thamesvalley.police.uk/', 'tel:101'),
  ('warwickshire', 'Warwickshire Police', 'https://www.warwickshire.police.uk/', 'tel:101'),
  ('west-mercia', 'West Mercia Police', 'https://www.westmercia.police.uk/', 'tel:101'),
  ('west-midlands', 'West Midlands Police', 'https://www.westmidlands.police.uk/', 'tel:101'),
  ('west-yorkshire', 'West Yorkshire Police', 'https://www.westyorkshire.police.uk/', 'tel:101'),
  ('wiltshire', 'Wiltshire Police', 'https://www.wiltshire.police.uk/', 'tel:101')
on conflict (id) do update set
  name = excluded.name,
  report_url = excluded.report_url,
  non_emergency_url = excluded.non_emergency_url;
